### ISSUE TITLE
Connection failure : ODBC Driver Manager not found Error

### ISSUE THREAD

**Issue by Salma-Bouzid** [exasol/sqlalchemy-exasol#100]
Hello, I am struggling to connect to an exasol database using sqlalchemy even though the Exasol ODBC driver 6.2.7 is already installed. I am also setting the driver name under EXASolution Driver in since this is how it exists in the ODBC  Data Source Administrator, but this outputted a similar error to the one below. Can you please let me know if I am making an error in the connection string? Or how do I make sure that the ODBC driver is correctly installed?

This is the connection string I am using: 

`from sqlalchemy import create_engine`

`engine = create_engine("exa+pyodbc://{username}:{password}@{host}:`
   `{port}/CONNECTIONLCALL=en_US.UTF- 8&driver=EXASolution Driver")`

`engine.connect()`

Error : 

`InterfaceError: (pyodbc.InterfaceError) ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
(Background on this error at: http://sqlalche.me/e/13/rvf5)`

Thank you for your help!

**Comment by fergarzag91** [comment]
Hi Salma,

A couple pointers/questions:

- The `UTF- 8` portion in your connection string has a space, is that a typo?
- Your driver name must be listed in your [odbcconfig/odbcinst.ini](https://github.com/blue-yonder/sqlalchemy_exasol/blob/master/odbcconfig/odbcinst.ini) file, the default driver name is EXAODBC and it's stored in [here](https://github.com/blue-yonder/sqlalchemy_exasol/tree/master/driver)
- The error suggests the odbcinst.ini file is incorrectly configured or not present. By the way, what system are you using this package on? I was a little confused by the **[Microsoft]** part as the usual is [unixODBC]

Thanks!

**Comment by Salma-Bouzid** [comment]
Hi @nndo1991 , thanks for getting back to me. 

 - The utf-8 was a typo in my issue text and not in the actual code. I am running the code on a windows machine. I installed the 
the ODBC driver from the official website of EXASOL but still the same error shows up. 
<img width="292" alt="odbc" src="https://user-images.githubusercontent.com/28934572/90233396-639f7080-de1e-11ea-8692-de3f6135877b.PNG">

I also installed the driver you referenced but I still get the same error. 
Do you have any more pointers? Much appreciated!

**Comment by fergarzag91** [comment]
Hi @Salma-Bouzid, we haven't tested this tool in Windows so far (whole team here is on Linux or Mac) but it should theoretically work.

Sqlalchemy uses pyodbc internally to establish connections to DBs, and everything in your error points to a driver setup issue. For that I would recommend some tests:

- Use the dockerfiles in this repo (which are unix-based) to build a Docker image and run the code from there
- Go one level deeper and try to connect to your DB straight from pyodbc (see step 5 of [this guide](https://datatofish.com/how-to-connect-python-to-sql-server-using-pyodbc/))
- Search for pyodbc issues on their repo, I actually had a similar issue to yours and found similar information [here](https://github.com/Microsoft/mssql-docker/issues/448)

Thanks!

**Comment by fergarzag91** [comment]
Closing this issue since it doesn't seem to be related to code in this repository
