### ISSUE TITLE
Discussion regarding has_table method for views

### ISSUE THREAD

**Issue by tkilias** [exasol/sqlalchemy-exasol#109]
Hello,

I would like to discuss the behavior of the `has_table` method 
at https://github.com/blue-yonder/sqlalchemy_exasol/blob/4ab21e05129e0b7976b7dd50c434a7e172535b06/sqlalchemy_exasol/base.py#L567.

We saw the following in issue in Apache Superset https://github.com/apache/superset/issues/16541. After some investigation, it looks like that Apache Superset expects the `has_table` method to return True if the given name either exists as Table, but also if it exists as View. 
- https://github.com/apache/superset/blob/be7065faf8e00ea0304b5380b2347f2ea9e4b39b/superset/connectors/sqla/utils.py#L46
- https://github.com/apache/superset/blob/be7065faf8e00ea0304b5380b2347f2ea9e4b39b/superset/models/core.py#L720

We also looked into the implementation of several other dialects and some of them show the same behavior. Here are some examples:

- Oracle: 
  - Uses [all_tables](https://docs.oracle.com/cd/B19306_01/server.102/b14237/statviews_2105.htm#REFRN20286) table which looks like it only contains tables and no views 
  - https://github.com/sqlalchemy/sqlalchemy/blob/6dbcb792eb60d4e084f0d1252882a0cbad4bc673/lib/sqlalchemy/dialects/oracle/base.py#L1612
- Postgresql:
  - Uses [pg_class](https://www.postgresql.org/docs/13/catalog-pg-class.html) table which can contain views and the query doesn't add any filters to it, so this would return true as well for views
  - https://github.com/sqlalchemy/sqlalchemy/blob/6dbcb792eb60d4e084f0d1252882a0cbad4bc673/lib/sqlalchemy/dialects/postgresql/base.py#L3349
- MySQL:
  - Uses [information_schema.tables](https://dev.mysql.com/doc/refman/8.0/en/information-schema-tables-table.html) which contains a TABLE_TYPE which can be a view and the code doesn't add any filters, so this returns True as well for views
  - https://github.com/sqlalchemy/sqlalchemy/blob/6dbcb792eb60d4e084f0d1252882a0cbad4bc673/lib/sqlalchemy/dialects/mysql/base.py#L2889

We also looked into the [sqlalchemy documentation](https://docs.sqlalchemy.org/en/14/core/internals.html#sqlalchemy.engine.Dialect.has_table) and it only speaks about tables. Views are not explicitly mentioned. So, we have at least some dialects which show a bit of different behavior and some tools seem to expect this behavior and others maybe not.

What do you think about this? Would a change make sense, or does it break to many existing things?

**Comment by Nicoretti** [comment]
Addressed by https://github.com/apache/superset/pull/16624, see also https://github.com/apache/superset/issues/16541#issuecomment-1121129954
