### ISSUE TITLE
Add job name to .github/workflows/CI-CD.yml

### ISSUE THREAD

**Issue by kaklakariada** [exasol/sqlalchemy-exasol#110]
github-keeper can only update the branch protection in this repo if a job name is defined in `.github/workflows/CI-CD.yml`:

`Validation Error for .github/workflows/CI-CD.yml: multi dimensional matrix github-action jobs with no explicit name are not supported. Please add a name field to the job that combines the matrix parameters into a more readable name. For example "Build with Go ${{matrix.go}} and Exasol ${{ matrix.db }}"`

**Comment by Nicoretti** [comment]
Fix can be validated using the following command `github-keeper configure-repo sqlalchemy-exasol`

**Comment by Nicoretti** [comment]
@kaklakariada the issue at hand was fixed, but `project-keeper` still could not validate it yet see https://github.com/exasol/github-keeper/issues/47
