### ISSUE TITLE
Upgrade to latest Exasol 7.1.x ODBC Driver

### ISSUE THREAD

**Issue by Nicoretti** [exasol/sqlalchemy-exasol#114]
# Summary
Upgrade to latest Exasol-7.1.x odbc driver

## Note
[Exasol-7.1.x-odbc-driver(s)](https://www.exasol.com/portal/display/DOWNLOAD/7.1) use TLS for database connections now as default.
Therefore pre existing connection setup's may fail now (see also [TLS/SSL and finger printing](https://community.exasol.com/t5/connect-with-exasol/tls-connection-fails/ta-p/6712)).

## Accaptance critera
* Integrate latest exasol 7.1.x ODBC driver into the project
* Document with which version of the exasol odbc driver this version of sqlalchemy-exasol was tested
* Make sure existing test and setup's within the project work fine with TLS

**Comment by tkilias** [comment]
This will probably get a bit tricky. To get the tests run we could disable the TLS verification, but to check if it is working, we probably need the generate credentials option of the integration test docker environment. You maybe can have a look at the pyexasol SSL tests.
