### ISSUE TITLE
Replace sql queries for metdata with odbc based metadata functions

### ISSUE THREAD

**Issue by Nicoretti** [exasol/sqlalchemy-exasol#139]
Information about the supported odbc metadata functions can be found [here](https://github.com/mkleehammer/pyodbc/wiki/Features-beyond-the-DB-API#miscellaneous-odbc-functions).

:spiral_notepad:  In case there will be issues with the odbc driver, add documentation for that.

List of known locations which need to be updated with odbc functions
* https://github.com/exasol/sqlalchemy-exasol/pull/137#discussion_r875801231
* https://github.com/exasol/sqlalchemy-exasol/pull/137#discussion_r875802278

**Comment by redcatbear** [comment]
In the light of the fact that we want this to be portable (e.g. web sockets), should we replace this?

**Comment by Nicoretti** [comment]
@redcatbear I the light that we want the web socket based variant as the main one I think we can close this issue.
