### ISSUE TITLE
Loosen version requirements on "packaging"

### ISSUE THREAD

**Issue by jochenott** [exasol/sqlalchemy-exasol#308]
"packaging" is currently pinned to >= 21.3,<22. OTOH, the only function used is `packaging.version.parse`, which rarely changes. So the version requirement on "packaging" is much tighter than required, making it harder than necessary to install sqlalchemy-exasol along other packages that also depend on "packaging".

I think the version requirement on "packaging" should be loosened, e.g. to >=21.3.

**Comment by Nicoretti** [comment]
Hi @jochenott,

thanks for the issue and the PR, I think you have a valid point there. I'll merge the PR later today.

best
Nico
