### ISSUE TITLE
Support turbodbc

### ISSUE THREAD

**Issue by pmetzner** [exasol/sqlalchemy-exasol#56]
> Currently only python 2.7 is supported by turbodbc and therefore for sqlalchemy-exasol, too.

Humble request: Since turbodbc now supports Python 3, can sqlalchemy-exasol extend the turbodbc support to Python 3, too?

**Comment by hoffmann** [comment]
I have activated the tests for turbodbc and python 3.4. There are three errors, but they do not seem to be critical:

https://travis-ci.org/blue-yonder/sqlalchemy_exasol/jobs/211250660

Did you try to use/install sqlalchemy with turbodbc and got any errors on python 3.x?

**Comment by pmetzner** [comment]
Awesome! Already tested it yesterday, this works like a charm:

```
cnxn = connect(dns)
crsr = cnxn.cursor()
crsr.execute('select 42')
crsr.fetchall()
```

**Comment by pmetzner** [comment]
Ah, I think I misread your question. I tried installing `sqlalchemy-exasol[turbodbc]` yesterday but it didn't offer the extra `turbodbc`. Now it did and it works. Did you change anything?

**Comment by pmetzner** [comment]
I had some trouble with the `DEFAULT_DRIVER_NAME` in `turbodbc.py`, I hotfixed it in #57.

**Comment by bjoernmeier** [comment]
Could you specify the problems you are having with the `DEFAULT_DRIVER_NAME `?
As `EXAODBC` is the default driver name provided by EXASOL and their driver package and you can overwrite it in you connection string I do not see a problem so far.

**Comment by bjoernmeier** [comment]
I close this ticket as python3 support is fixed and the default driver name can be overwritten.
