### ISSUE TITLE
Default: CONNECTIONLCALL=en_US.UTF-8

### ISSUE THREAD

**Issue by jank** [exasol/sqlalchemy-exasol#65]
Using 'CONNECTIONLCALL=en_US.UTF-8' as query parameter for connection URLs is a reliable way of making sure that Python process and EXASOL driver agree on a common encoding (at least on Linux/Unix). 

Add this as documentation or even default to have less pain with running into conversion errors.

**Comment by MathMagique** [comment]
Compare http://turbodbc.readthedocs.io/en/latest/pages/databases/exasol.html

**Comment by jank** [comment]
Implemented in 1.2.3
