### ISSUE TITLE
Unable to reflect views

### ISSUE THREAD

**Issue by oliver-frost** [exasol/sqlalchemy-exasol#70]
According to
http://docs.sqlalchemy.org/en/latest/core/reflection.html#reflecting-views
sqlalchemy should be able to reflect views, as if they were tables in the database.

However the exasol dialect does not support the reflection of views.
In particular it already claims, that views that are present on the database do not exist. You may reproduce this undesirable behavior like:
```
import sqlalchemy
uri = "exa+pyodbc://my_dsn"
schema = "my_schema"
engine = sqlalchemy.create_engine(uri)
meta_data = sqlalchemy.MetaData(bind=engine, schema=schema)
view_name = "my_view"
view = sqlalchemy.Table(view_name, meta_data)
assert(view.exists()) # Fires for every view
```

**Comment by exaSR** [comment]
Does it also fail when passing the view name in 'proper' uppercase?
It is possible that the reflection part is performing the lookups with case-sensitive names.
(no sqlalchemy to test here)

**Comment by oliver-frost** [comment]
No. The uppercase view_name also fails.
The same check for proper tables is also independent of the capitalization.

**Comment by jank** [comment]
I suggest to trace through the SQLA and sqlalchemy_exasol dialect. I suspect, that the dialect & SQLA are trying to find a 'TABLE' with name 'my_view'. As this does not exist, it returns false. 

You could try to reflect all views using `get_view_names(self, connection, schema=None, **kw)`. Note that this requires a proper schema. This should at least produce the names of all views in the schema.

**Comment by oliver-frost** [comment]
Yes. To find out whether the view exist it is sufficient to query the Inspector interface using get_view_names, but it would not give me the column definitions and ORM, etc.

**Comment by jank** [comment]
I will close this as won't fix. The current implementation of SQLA up to 1.3 is inconsistent. The implementation for Table.exists() explicitly only checks for existence of tables, not views. Hence, returning `false`is consistent with the intent of the implementation but highly confusing. The current development branch 1.4 deprecates `Table.exists()`.
Thus, the decision to not fix this.
