### ISSUE TITLE
Avoid DB locks when performing metadata queries on SYS tables

### ISSUE THREAD

**Issue by jank** [exasol/sqlalchemy-exasol#89]
The default locking behavior of Exasol is to create table locks. 

When running queries with a high degree of concurrent connections on the same tables, deadlock situations can occur. This can be observed, e.g. when using BI tools that excessively query metadata tables.

To avoid deadlocks with pure read queries, select statements on SYS tables should be prepended with the DB hint `/*snapshot execution*/`. Starting with Exasol 6.2.5 the DB will execute these statements in a snapshot isolation mode, effectively avoiding creation of locks.

The idea for implementation is to prepend select statements on SYS tables with the pseudo comment `/*snapshot execution*/`.

Things to clarify & explore before implementation:

* details on the snapshot execution feature documented here https://www.exasol.com/support/browse/EXASOL-2646
* what is the DB version of the test DB?
* should the pseudo comment only be generated for DB versions >= 6.2.5 or even for older versions (that will ignore this comment)?
* how can this be tested given that the deadlock situations only occur in situations of excessive concurrency? (e.g. are they ways to inspect the query plan to check if snapshot isolation is active)
* which type of queries should be covered (e.g. only SELECT)?
* how should queries be treated that query/merge other tables besides tables residing in `SYS`?
* what are potential side-effects on the SQLA test suite that heavily uses metadata queries to test the effects of DDL statements, e.g. are the changes to the data catalog visible when running in snapshot isolation?
* potential places for implementation
  * the pre_exec() method could be a potential place for the injection: https://github.com/blue-yonder/sqlalchemy_exasol/blob/master/sqlalchemy_exasol/base.py#L336
  * the reflection methods of the EXADialect class (e.g. manually insert the pseudo comment to all select statements) https://github.com/blue-yonder/sqlalchemy_exasol/blob/master/sqlalchemy_exasol/base.py#L375
* consider using the prefix_with() method available on all selectables https://docs.sqlalchemy.org/en/13/core/selectable.html?highlight=prefix#sqlalchemy.sql.expression.Select.prefix_with

**Comment by tkilias** [comment]
The pull request #90 reimplements the metadata functions with ODBC Functions for pyodbc which avoid DB locks.
