### ISSUE TITLE
Release a 3.0.0 version that drops Python 2.7 support

### ISSUE THREAD

**Issue by jank** [exasol/sqlalchemy-exasol#93]

**Comment by jank** [comment]
Dropping support for Python 2.7 would slash the CI pipeline into half.

**Comment by jank** [comment]
https://github.com/blue-yonder/sqlalchemy_exasol/pull/107 dropped Python 2.7 support. @bjoern-meier-by

**Comment by bjoernmeier** [comment]
With 3.0.0 might come other possible breaking changes:
* sqlalchemy only 1.4.x support (we might not be able to support <1.4 and > 1.4 without too many code paths)
* drop support of exasol < 4.1.8 as the code from https://github.com/blue-yonder/sqlalchemy_exasol/blob/master/sqlalchemy_exasol/base.py#L349 has to go

**Comment by jank** [comment]
Please note that https://github.com/blue-yonder/sqlalchemy_exasol/blob/master/sqlalchemy_exasol/base.py#L349 kicks in for two conditions:
* EXASOL server < 4.1.8
* or DELETE statement
@tkilias - can you check if performance for DELETE statements improved with versions 6.x or 7.x? If not I am afraid we need to keep this ugly code switch.

**Comment by jank** [comment]
Duplicate of #106

This is a duplicate of above issue, but this one provides some context on how to tackle support for SQLAlchemy 1.4
