### ISSUE TITLE
Improve CI and CI/CD pipelines

### ISSUE THREAD

**Issue by fergarzag91** [exasol/sqlalchemy-exasol#99]
Had a conversation with Frank Fischer and he suggested a couple changes for the project:

- Remove manual stuff like git clone and pip install and replace them with public github actions like checkout@v2 already used
- Cache all installation of requirements
- Use a pre-commit hook to remove trailing spaces and alert about other formatting issues
- Figure out way to pull newest versions of public actions
- Figure out way to restrict tagging by contributors so not anyone can publish to PyPi

**Comment by fergarzag91** [comment]
This enhancement is still pending as I never got to work on it

**Comment by jank** [comment]
Move to GitHub Actions done
